# $Id: Makefile.athena,v 1.2 1996-11-20 15:41:24 ghudson Exp $

SHELL=/bin/sh

prepare:

clean:
	${MAKE} -f Makefile.ini clean

all:
	${MAKE} -f Makefile.ini imake CC="$$COMPILER"

check:

install:
	mkdir -p "$$SRVD/usr/athena/bin"
	install -c -m 555 imake "$$SRVD/usr/athena/bin"
